
[[article]]
slug = "retool"
file = "1-retool.md"
title = "Retool: Raising less money at lower valuations"
author = "Folyd"
cover = "/static/s1/1/retool.png"
pub_date = "2021-12-23"
publish = true
featured = true

[[article]]
slug = "cncf"
file = "2-cncf.md"
title = "CNCF 的愿景：技术变革与对抗熵增"
author = "Folyd"
cover = "/static/s1/2/specs.png"
pub_date = "2021-12-29"
publish = true
featured = true

[[article]]
slug = "hashicorp"
file = "3-hashicorp.md"
title = "时势造英雄-HashiCorp"
author = "Folyd"
cover = "/static/s1/3/ipo.png"
pub_date = "2022-01-06"
publish = true
featured = true

[[article]]
slug = "kong-vs-apisix"
file = "4-kong-vs-apisix.md"
title = "云原生时代的中外 API 网关之争"
author = "Folyd"
cover = "/static/s1/4/vs.png"
pub_date = "2022-01-13"
publish = true
featured = true

[[article]]
slug = "coreos"
file = "5-coreos.md"
title = "云原生的一代传奇 CoreOS"
author = "Folyd"
cover = "/static/s1/5/product.png"
pub_date = "2022-01-20"
publish = true
featured = true

[[article]]
slug = "docker"
file = "6-docker.md"
title = "一封 Docker 公司的来信"
author = "Folyd"
cover = "/static/s1/6/docker.jpeg"
pub_date = "2022-01-27"
publish = true
featured = true
