
[[article]]
slug = "retool"
file = "1-retool.md"
title = "Retool: Raising less money at lower valuations"
author = "Folyd"
cover = "/static/s1/1/retool.png"
pub_date = "2021-12-23"
publish = true
featured = true