
[site]
url = "https://2d2d.io"
name = "TO-D 杂志"
description = "专注于探讨全球 To-D 领域相关产品、创业公司、融资等资讯的专栏杂志。"
locale = "zh"
menu = [
  { name = "关于", url = "/about" },
  { name = "博客", url = "/blog" },
  { name = "读者好评", url = "/testimonial" },
  { name = "赞助", url = "/sponsor" },
  { name = "Github", url = "https://github.com/zineland/2d2d" },
]

[theme]
primary-color = "#ffb52f"
main-color = "#000"
link-color = "#e07312"
background-image = "/static/pattern.svg"
footer-template = "templates/footer.html"

[[issue]]
slug = "s1"
number = 1
title = "第一季"
path = "content/issue-1"
intro = "content/issue-1/intro.md"

[[issue]]
slug = "s2"
number = 2
title = "第二季"
path = "content/issue-2"
